# -*- coding: utf-8 -*-
"""PriceOptima_ProductData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uiR1h6ewEWPC7rwDpZGmfoXs9Bk6JS5L
"""

from google.colab import drive
drive.mount('/content/drive')
print("Drive mounted")

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Dynamic pricing /Product Data.csv')
print("File loaded")

df.head()

df.tail()

df.shape

df.describe()

df.isnull().sum()

print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates after:", df.duplicated().sum())
print("New shape:", df.shape)

df.columns

df.dtypes

numeric_cols = ['Original_Price','Competitor_Price','Historical_Sales','Sales_After_M1','Sales_After_M2',
                'Sales_After_M3','Sales_After_M4','Stock_Level','Customer Ratings','Return Rate','Optimal Discount']

import matplotlib.pyplot as plt
import seaborn as sns

for col in numeric_cols:
    plt.figure(figsize=(6,3))
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot of {col}')
    plt.show()

for col in numeric_cols:
    lower = df[col].quantile(0.01)
    upper = df[col].quantile(0.99)
    df[col] = df[col].clip(lower, upper)

for col in numeric_cols:
    print(f"{col} min: {df[col].min()}, max: {df[col].max()}")

assert (df['Historical_Sales'] >= 0).all()
assert (df[['Sales_After_M1','Sales_After_M2','Sales_After_M3','Sales_After_M4']] >= 0).all().all()
assert (df['Original_Price'] > 0).all()
assert (df['Competitor_Price'] > 0).all()
assert (df['Return Rate'].between(0,100)).all()
assert (df['Customer Ratings'].between(0,5)).all()
assert (df['Optimal Discount'].between(0,100)).all()

df['Total_Sales_After'] = df[['Sales_After_M1','Sales_After_M2','Sales_After_M3','Sales_After_M4']].sum(axis=1)
df['Avg_Markdown'] = df[['Markdown_1','Markdown_2','Markdown_3','Markdown_4']].mean(axis=1)

df.to_csv('Cleaned_ProductData.csv', index=False)

