# -*- coding: utf-8 -*-
"""PriceOptima_RetailStoreInventory_Validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dPH5UJEhvIJmEWhvWzW76c7rtTnyE2c1
"""

from google.colab import drive
drive.mount('/content/drive')
print("Drive mounted")

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Dynamic pricing /retail_store_inventory.csv')
print("File loaded")

df.head()

df.tail()

df.shape

df.describe()

df.columns

df.isnull().sum()

print("Duplicates before:", df.duplicated().sum())

df.dtypes

# Converting object into date time type for date column
df['Date'] = pd.to_datetime(df['Date'])

df.dtypes

categorical_cols = ['Category', 'Region', 'Seasonality']
for col in categorical_cols:
    print(col, df[col].unique())

"""Check and Handle Outliers"""

numeric_cols = ['Units Sold', 'Inventory Level', 'Price', 'Competitor Pricing']

import matplotlib.pyplot as plt
import seaborn as sns

for col in numeric_cols:
    plt.figure(figsize=(6,3))
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot of {col}')
    plt.show()

for col in numeric_cols:
    lower = df[col].quantile(0.01)
    upper = df[col].quantile(0.99)
    df[col] = df[col].clip(lower, upper)

for col in numeric_cols:
    print(f"{col} min: {df[col].min()}, max: {df[col].max()}")

invalid_sales = df[df['Units Sold'] > df['Inventory Level']]
print("Rows where Units Sold > Inventory Level:", len(invalid_sales))

# Check invalid prices
invalid_prices = df[df['Price'] <= 0]
print("Rows with non-positive Price:", len(invalid_prices))

invalid_discount = df[~df['Discount'].between(0, 100)]
print("Rows with invalid Discount:", len(invalid_discount))

invalid_competitor_price = df[df['Competitor Pricing'] <= 0]
print("Rows with invalid Competitor Pricing:", len(invalid_competitor_price))

df = df.sort_values(['Store ID','Product ID','Date'])
duplicates = df.duplicated(subset=['Store ID','Product ID','Date']).sum()
print("Duplicate rows by Store, Product, Date:", duplicates)

df['Revenue'] = df['Units Sold'] * df['Price']
df['Discounted_Price'] = df['Price'] * (1 - df['Discount']/100)

df.head()

df.to_csv('Cleaned_Retail_Store_Inventory.csv', index=False)

