# -*- coding: utf-8 -*-
"""Baseline Pricing Engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bn7E7nydl2njWbTPpfRDcwFQ3cgX8JGE
"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Dynamic pricing /PriceOptima_FeatureEngineered_Final.csv")

"""Rule-Based Pricing Implementation"""

import numpy as np
import pandas as pd

# Copy original price
df['rule_price'] = df['Price']

# -------------------------
# TIME-BASED PRICING RULES
# -------------------------

# Weekend price increase (+5%)
df.loc[df['is_weekend'] == 1, 'rule_price'] *= 1.05

# Holiday / promotion price increase (+8%)
df.loc[df['is_holiday'] == 1, 'rule_price'] *= 1.08

# Peak season pricing (+5%)
df.loc[(df['season_Winter'] == 1) | (df['season_Summer'] == 1), 'rule_price'] *= 1.05

# Month-end pricing (+3%)
df.loc[df['day'] >= 25, 'rule_price'] *= 1.03

# Low-demand discount (-5%)
low_demand_threshold = df['Units Sold'].quantile(0.25)
df.loc[df['Units Sold'] < low_demand_threshold, 'rule_price'] *= 0.95


# -------------------------
# INVENTORY-BASED PRICING RULES
# -------------------------

# Low stock pricing (+10%)
df.loc[df['low_stock_flag'] == 1, 'rule_price'] *= 1.10

# Overstock clearance pricing (-15%)
df.loc[df['overstock_flag'] == 1, 'rule_price'] *= 0.85

# Revenue calculations
df['static_revenue'] = df['Price'] * df['Units Sold']
df['rule_based_revenue'] = df['rule_price'] * df['Units Sold']

# Aggregate revenue
total_static_revenue = df['static_revenue'].sum()
total_rule_revenue = df['rule_based_revenue'].sum()

revenue_comparison = pd.DataFrame({
    'Pricing Strategy': ['Static Pricing', 'Rule-Based Pricing'],
    'Total Revenue': [total_static_revenue, total_rule_revenue]
})

revenue_comparison

revenue_lift_pct = (
    (total_rule_revenue - total_static_revenue) / total_static_revenue
) * 100

revenue_lift_pct

print(f"Revenue lift percentage after rule based pricing is {revenue_lift_pct:.2f} %")

