# -*- coding: utf-8 -*-
"""EDA.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DkMWTzGNW9-FU0e5xg4cIZaBOMeXNFXY
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Dynamic pricing /PriceOptima_FeatureEngineered_Final.csv")

df.head()

df.tail()

df.shape

df.info()

df.describe().T

"""Target Variable Analysis: Units Sold

From the describe table

| Metric  | Value      | Interpretation               |
| ------- | ---------- | ---------------------------- |
| Mean    | **136.25** | Average daily demand         |
| Median  | **107**    | Distribution is right-skewed |
| Std Dev | **108.27** | High demand variability      |
| Min     | **1**      | Very low demand days exist   |
| Max     | **434**    | Peak demand days             |

Mean > Median → Right-skewed distribution

Few very high-demand days drive the average
"""

#Distribution Shape
df["Units Sold"].quantile([0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99])

"""Observation
- Bottom 1% of days sell only 1 unit
- Median demand is 107 units
- Top 1% reaches 434 units

Insight
- Demand is highly right-skewed, with a small fraction of days driving very high sales.
- This indicates demand spikes due to promotions, seasonality, or pricing actions, rather than consistent daily demand.
- Inventory and staffing should be planned around peak-demand scenarios, not averages.
- Safety stock is essential to handle top 5–10% demand days.
"""

# Yearly Demand Trend
df.groupby("year")["Units Sold"].mean()

"""- Demand remains largely stable across years, with a slight decline in 2024.

- No structural demand collapse or abnormal growth is observed.
"""

# Monthly Seasonality
df.groupby("month")["Units Sold"].mean()

"""Observation

- Monthly averages range narrowly between ~133 to ~139 units

- Slight peaks around February, July, November

- Lowest demand in December and April–May

Insight

- Demand shows mild seasonality, not extreme monthly fluctuations.

- Seasonality affects demand incrementally rather than drastically.
"""

# Weekend Effect
df.groupby("is_weekend")["Units Sold"].mean()

"""Insight

- Demand is nearly identical on weekends and weekdays.

- No strong weekend-driven consumption behavior is observed.
"""

#Holiday / Promotion Effect
df.groupby("Holiday/Promotion")["Units Sold"].mean()

"""Insight

- Holidays and promotions do not significantly increase average units sold.

- Promotional impact appears muted or diluted across the dataset.
"""

# Units Sold vs Price
df.groupby(pd.qcut(df["Price"], 5))["Units Sold"].mean()

"""Observation

- Average units sold remains nearly constant across all price bins.

Insight

- Demand appears price-inelastic at the aggregated level.

- Customers are not strongly sensitive to price changes in isolation.
"""

# Units Sold vs Discount
df.groupby("Discount")["Units Sold"].mean()

"""Observation

- Average units sold remains nearly constant across all price bins.

Insight

- Demand appears price-inelastic at the aggregated level.

- Customers are not strongly sensitive to price changes in isolation.
"""

# Inventory Sanity Check
df.groupby("low_stock_flag")["Units Sold"].mean()

"""Insight

- Low inventory days experience significantly lower sales.

- Demand is being supply-constrained, not demand-constrained.
"""

df.columns

# Overall Elasticity Distribution
# Elasticity distribution (summary)
df['avg_price_elasticity'].describe()

"""Overall demand is price elastic, meaning changes in price significantly impact units sold.

The wide range indicates heterogeneous product behavior, justifying a dynamic pricing strategy instead of fixed pricing.

Extreme values suggest certain products are highly sensitive to pricing changes and should be priced cautiously.
"""

# Count of elasticity classes
df['elasticity_class_Medium'].value_counts()

"""Only a small subset of products falls into the medium elasticity class.

Most products exhibit either low or high elasticity, meaning they respond sharply to price changes.

This supports product-level pricing optimization rather than category-level pricing.
"""

elasticity_cols = [col for col in df.columns if col.startswith('elasticity_class')]
df[elasticity_cols].sum()

"""Only a small subset of products falls into the medium elasticity class.

Most products exhibit either low or high elasticity, meaning they respond sharply to price changes.

This supports product-level pricing optimization rather than category-level pricing.
"""

# Category-wise Elasticity Analysis
category_cols = [
    'Category_Electronics',
    'Category_Furniture',
    'Category_Groceries',
    'Category_Toys'
]

category_elasticity = {}

for col in category_cols:
    category_elasticity[col.replace('Category_', '')] = (
        df.loc[df[col] == 1, 'avg_price_elasticity'].mean()
    )

category_elasticity_df = (
    pd.DataFrame.from_dict(category_elasticity, orient='index', columns=['avg_elasticity'])
    .sort_values('avg_elasticity')
)

category_elasticity_df

"""Electronics are the most price-sensitive, likely due to higher price awareness and comparison behavior.

Toys and furniture show relatively lower sensitivity, allowing for more pricing flexibility.

Category-specific pricing rules should be applied rather than uniform discounts.
"""

# Region-wise Elasticity
region_cols = ['Region_North', 'Region_South', 'Region_West']

region_elasticity = {}

for col in region_cols:
    region_elasticity[col.replace('Region_', '')] = (
        df.loc[df[col] == 1, 'avg_price_elasticity'].mean()
    )

region_elasticity_df = (
    pd.DataFrame.from_dict(region_elasticity, orient='index', columns=['avg_elasticity'])
    .sort_values('avg_elasticity')
)

region_elasticity_df

"""Southern region customers are most price-sensitive, possibly due to higher competition or budget-conscious behavior.

Regional pricing adjustments can improve revenue without hurting demand uniformly.
"""

# Season-wise Elasticity
season_cols = ['season_Spring', 'season_Summer', 'season_Winter']

season_elasticity = {}

for col in season_cols:
    season_elasticity[col.replace('season_', '')] = (
        df.loc[df[col] == 1, 'avg_price_elasticity'].mean()
    )

season_elasticity_df = (
    pd.DataFrame.from_dict(season_elasticity, orient='index', columns=['avg_elasticity'])
    .sort_values('avg_elasticity')
)

season_elasticity_df

"""Products with low stock are more price-sensitive, indicating customers react strongly when availability is limited.

This supports dynamic price increases during low stock to balance demand and inventory.
"""

# Inventory Constraint vs Elasticity
df.groupby('low_stock_flag')['avg_price_elasticity'].mean()

"""Products with low stock are more price-sensitive, indicating customers react strongly when availability is limited.

This supports dynamic price increases during low stock to balance demand and inventory.
"""

# Discount Sensitivity vs Elasticity
# Bucket discount levels
df['discount_bucket'] = pd.cut(
    df['discount_pct'],
    bins=[0, 0.05, 0.10, 0.15, 0.20],
    labels=['0–5%', '5–10%', '10–15%', '15–20%'],
    include_lowest=True
)

df.groupby('discount_bucket')['avg_price_elasticity'].mean()

"""Moderate discounts (10–15%) reduce price sensitivity.

Very high discounts (15–20%) increase elasticity again, suggesting over-discounting leads to unstable demand behavior.

Optimal discounts should stay in the mid-range.
"""

# Profitability vs Elasticity (Key Business Insight)
df.groupby('elasticity_class_Medium').agg({
    'Units Sold': 'mean',
    'profit_per_unit': 'mean',
    'daily_profit': 'mean'
})

"""Medium elasticity products generate positive profit per unit and daily profit.

Highly elastic or inelastic products show profit erosion.

Pricing models should prioritize medium elasticity products for margin optimization.
"""

# High-Level Segmentation Table (FINAL)
segmentation_summary = df.groupby([
    'low_stock_flag',
    'is_weekend',
    'is_holiday'
]).agg({
    'Units Sold': 'mean',
    'avg_price_elasticity': 'mean',
    'profit_margin': 'mean'
}).reset_index()

segmentation_summary

"""Pricing decisions must consider multiple interacting factors, not single variables.

Weekends and holidays amplify elasticity effects, especially for low-stock items.

Reinforces need for context-aware pricing models.
"""

# Correlation Check (Elasticity Drivers)
elasticity_features = [
    'Price',
    'discount_pct',
    'inventory_ratio',
    'sales_volatility_7',
    'sales_volatility_30',
    'avg_demand_7d',
    'profit_margin'
]

df[elasticity_features + ['avg_price_elasticity']].corr()['avg_price_elasticity']

"""Elasticity is weakly correlated with individual variables.

Indicates non-linear, multi-factor dependency, validating use of tree-based ML models (XGBoost / LightGBM).
"""

df['avg_price_elasticity'].quantile([0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99])

"""Bottom percentile products are extremely price-sensitive → price changes should be minimal.

Top percentile shows positive elasticity, possibly luxury or necessity items where demand increases with price perception.

Reinforces segmented pricing strategies.
"""

