# -*- coding: utf-8 -*-
"""LightGBM.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1Nd5vAgrnYq4ox35m_kf5AxYoAzDCQP
"""

import pandas as pd
import numpy as np

from lightgbm import LGBMRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error

df = pd.read_csv("/content/drive/MyDrive/Dynamic pricing /PriceOptima_FeatureEngineered_Final.csv",parse_dates=['Date'])
df = df.sort_values('Date').reset_index(drop=True)
print(df.shape)

print("Missing values:", df.isnull().sum().sum())
print("Duplicates:", df.duplicated().sum())

y = df['Units Sold']

drop_cols = ['Units Sold', 'Revenue', 'daily_profit']  # avoid leakage
X = df.drop(columns=drop_cols)

# Drop unsupported columns for LGBM (same as XGBoost)
X = X.drop(columns=['Date', 'Seasonality'], errors='ignore')

print(X.shape, y.shape)

split_date = df['Date'].quantile(0.80)

X_train = X[df['Date'] <= split_date]
X_test  = X[df['Date'] > split_date]

y_train = y[df['Date'] <= split_date]
y_test  = y[df['Date'] > split_date]

print("Train:", X_train.shape)
print("Test :", X_test.shape)

lgbm_model = LGBMRegressor(
    n_estimators=800,
    learning_rate=0.03,
    num_leaves=63,
    max_depth=-1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

lgbm_model.fit(X_train, y_train)

y_pred = lgbm_model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)

print("LightGBM RMSE:", rmse)
print("LightGBM MAE :", mae)

test_df = df[df['Date'] > split_date].copy()
test_df['predicted_demand'] = y_pred

# Demand ratio based pricing
demand_ratio = test_df['predicted_demand'] / test_df['avg_demand_7d']

test_df['ml_price'] = test_df['Price'] * (1 + 0.05 * (demand_ratio - 1))

# Safety cap (prevent extreme prices)
test_df['ml_price'] = test_df['ml_price'].clip(
    lower=0.8 * test_df['Price'],
    upper=1.2 * test_df['Price']
)

# Price change distribution check
test_df['price_change_pct_ml'] = (test_df['ml_price'] - test_df['Price']) / test_df['Price'] * 100
test_df['price_change_pct_ml'].describe()

test_df['static_revenue'] = test_df['Price'] * test_df['Units Sold']
test_df['ml_revenue'] = test_df['ml_price'] * test_df['Units Sold']

static_total = test_df['static_revenue'].sum()
ml_total = test_df['ml_revenue'].sum()

revenue_lift_pct = (ml_total - static_total) / static_total * 100

static_total, ml_total, revenue_lift_pct

revenue_comparison = pd.DataFrame({
    "Pricing Strategy": ["Static Pricing", "ML-Based Pricing (LightGBM)"],
    "Total Revenue": [static_total, ml_total]
})

revenue_comparison

test_df['ml_action'] = np.where(
    test_df['ml_price'] > test_df['Price'], 'Increase',
    np.where(test_df['ml_price'] < test_df['Price'], 'Decrease', 'No Change')
)

(test_df['ml_action'].value_counts(normalize=True) * 100).to_frame("proportion")

test_df.to_csv("PriceOptima_LightGBM_Backtest.csv", index=False)
print("Saved: PriceOptima_LightGBM_Backtest.csv")

